name: udisks
version: 0.3.1

description:
  Provides a client to connect to UDisks - the service that accesses and manipulates disks, storage devices and technologies on Linux.

homepage: https://github.com/canonical/udisks.dart

environment:
  sdk: '>=2.14.0 <3.0.0'

platforms:
  linux:

dependencies:
  dbus: ^0.7.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.8
  test_cov: ^1.0.1

